
title: Programma Generator
email: jens.dufour@outlook.com
description: >-
  A generator for our six weekly program.
baseurl: "/Programma"
url: "https://jensdufour.github.io"
github_username:  jensdufour

# Build settings
markdown: kramdown
theme: minima
